alumno/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import login


app_name = 'alumno'
urlpatterns = [

    path('home/', views.home, name="home"),
    path('lista_profesores/', views.lista_profesores, name="lista_profesores"),
    path('calendario/(?P<num_semana>\d+)/', views.calendar, name="calendario"),
    path('favoritos/', views.favoritos, name="favoritos"),
    path('historial/', views.historial, name="historial"),
    path('register/', views.register, name='register'),
    path('login/',  views.login, name='login'),
    path('log_out/',  views.log_out, name='log_out'),



    path('perfil_profesor/(?P<pk_profesor>\w+)/', views.perfil_profesor, name="perfil_profesor"),
    path('agregar_cita/(?P<asesoria>\w+)/', views.agregar_cita, name="agregar_cita"),
    path('agregar_favorito/(?P<asesoria>\w+)/', views.agregar_favorito, name="agregar_favorito"),
    path('eliminar_favorito/(?P<favorito>\w+)/', views.eliminar_favorito, name="eliminar_favorito"),
    path('eliminar_cita/(?P<cita>\w+)/', views.eliminar_cita, name="eliminar_cita"),
    path('finalizar_cita/(?P<cita>\w+)/', views.finalizar_cita, name="finalizar_cita"),

]

asesoria/urls.py
from django.contrib import admin
from django.urls import path, include
from asesoria import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('alumno/', include('alumno.urls', namespace='alumno')),
    path('profesor/', include('profesor.urls', namespace='profesor')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

profesor/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import login


app_name = 'profesor'
urlpatterns = [

    path('home/', views.home),
    path('login/', views.login),
    path('citas/', views.citas),
    path('calendario/(?P<num_semana>\d+)/', views.calendar, name="calendario"),
    path('historial/', views.historial),
    path('log_out/',  views.log_out, name='log_out'),
    path('change_state/',  views.change_state),


    path('perfil_profesor/', views.perfil_profesor, name="perfil_profesor"),
    path('eliminar_cita/(?P<cita>\w+)/', views.eliminar_cita, name="eliminar_cita"),

]

alumno/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from  profesor.models import *
#from django.contrib.auth.model import User
# Create your models here.

#class UserProfile(models.Model):

#    USERS_TYPE = ('Alumno','Profesor')

    #user = models.OnetoOneField(User)
    #tipo = (models.chartField(max_legnth=10, choices = USERS_TYPE))
    #carrera = models.chartField(default=10)

class Alumno(models.Model):
    nombre = models.CharField(max_length=60)
    apellido = models.CharField(max_length=50)
    password = models.CharField(max_length=20)
    codigoUlima  = models.CharField(max_length=20, unique=True)
    email  = models.CharField(max_length=30, unique=True)


    def __str__(self):
        return "PK: {}, Nombre: {}, Código: {}".format(self.pk, self.nombre, self.codigoUlima)

    @staticmethod
    def verify_user(codigoUlima, password):
        alumno = Alumno.objects.filter(codigoUlima=codigoUlima).first()
        return alumno != None and alumno.password == password, alumno

class Cita(models.Model):
    asesoria = models.ForeignKey(Asesoria, on_delete=models.CASCADE)
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)
    semana = models.IntegerField()
    finalizado = models.BooleanField(default=False)
    #PUEDE MEJORARSE
    tema = models.CharField(max_length=300)

    class Meta:
        unique_together = ('asesoria', 'alumno',)

    def __str__(self):
        return "Asesoria: {}, Alumno: {}".format(self.asesoria, self.alumno)


class Favorito(models.Model):
    asesoria = models.ForeignKey(Asesoria, on_delete=models.CASCADE)
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('asesoria', 'alumno',)

    def __str__(self):
        return "Asesoria: {}, Alumno: {}".format(self.asesoria, self.alumno)


class Comentario(models.Model):

    cita = models.ForeignKey(Cita, on_delete=models.CASCADE)
    rate = models.IntegerField()
    comment = models.CharField(max_length = 200)

profesor/models.py
from django.db import models
# Create your models here.


class Profesor(models.Model):

    state_options = (
        ('Disponible', 'Disponible'),
        ('Ocupado', 'Ocupado'),
        ('Ausente', 'Ausente'),
        ('No disponible', 'No disponible'),
    )

    nombrepProfesor = models.CharField(max_length=60)
    password = models.CharField(max_length=20)
    codigoUlima  = models.CharField(max_length=20, unique=True)
    email  = models.CharField(max_length=30, unique=True)
    state = models.CharField(max_length=20, choices=state_options)
    image = models.ImageField(upload_to="profesores/")

    def __str__(self):
        return "PK: {}, Nombre: {}, Código ULima: {}".format(self.pk, self.nombrepProfesor, self.codigoUlima)

    @staticmethod
    def verify_user(codigoUlima, password):
        profesor = Profesor.objects.filter(codigoUlima=codigoUlima).first()
        return profesor != None and profesor.password == password, profesor

class Curso(models.Model):
    nombreCurso = models.CharField(max_length=50)
    seccion = models.IntegerField()
    codProfesor = models.ForeignKey(Profesor, on_delete=models.CASCADE)

    def __str__(self):
        return "Nombre del Curso: {}".format(self.nombreCurso)

class Salon(models.Model):
    lugar = models.CharField(max_length = 10, unique= True)

    def __str__(self):
        return "Lugar: {}".format(self.lugar)

class Asesoria(models.Model):
    dia_semana = (
        ('Lunes', 'Lunes'),
        ('Martes', 'Martes'),
        ('Miércoles', 'Miércoles'),
        ('Jueves', 'Jueves'),
        ('Viernes', 'Viernes'),
    )

    codProfesor = models.ForeignKey( Profesor, on_delete=models.CASCADE)
    codCurso= models.ForeignKey(Curso, on_delete=models.CASCADE,)
    fechaAsesoria = models.CharField(max_length=12, choices=dia_semana)
    horaInicio = models.TimeField(default="12:00")
    lugar = models.ForeignKey(Salon, on_delete=models.CASCADE)

    def __str__(self):
        return "PK: {}, Profesor: {}, Curso".format(self.pk, self.codProfesor, self.codCurso)

profesor/forms.py
from django import forms
from profesor.models import *
# from django.contrib.auth.models import User

class LoginForm(forms.Form):
    codigoUlima = forms.CharField(label='Código ULima', required=True)
    password = forms.CharField(label='Contraseña', required=True)

    class Meta:
        model = Profesor
        fields = {
            'codigoUlima',
            'password'
        }

profesor/views.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from profesor.forms import *
from profesor.models import *
from alumno.models import Cita
import datetime
# Create your views here.

inicio_clases = datetime.datetime(2018, 8, 6)

PROFESOR = 'PROFESOR'


def home(request):
    delta_date = datetime.datetime.now() - inicio_clases
    num_semana = round(delta_date.days / 7)
    user_id = request.session.get('user', None)
    type = request.session.get('type', None)
    if type == PROFESOR:
        user = Profesor.objects.filter(pk=user_id).first()
        if user != None:
            return render(request,'profesor/Tony/home.html', {"usuario": user, "num_semana": num_semana})
    return redirect('/profesor/login')


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            codigoUlima = form.cleaned_data['codigoUlima']
            password = form.cleaned_data['password']
            boo, profesor = Profesor.verify_user(codigoUlima, password)
            if boo:
                request.session['user'] = profesor.pk
                request.session['type'] = PROFESOR
                return redirect('/profesor/home')

    form = LoginForm()
    args = {'form': form}
    return render(request,'profesor/login.html', args)

def historial(request):
    user_id = request.session.get('user', None)
    user = Profesor.objects.filter(pk=user_id).first()
    if user != None:
        args = {"citas": citas, "usuario": user}
        return render(request, 'profesor/Tony/historial.html', args)
    return redirect('/profesor/login')

def citas(request):
    user_id = request.session.get('user', None)
    user = Profesor.objects.filter(pk=user_id).first()
    if user != None:
        asesorias = user.asesoria_set.all()
        args = {"asesorias": asesorias, "usuario": user}
        return render(request, 'profesor/Tony/citas.html', args)
    return redirect('/profesor/login')

def eliminar_cita(request, cita):
    Cita.objects.get(pk=cita).delete()
    return redirect('/profesor/citas')

@csrf_exempt
def change_state(request):
    state = request.POST['state']
    user_id = request.session.get('user', None)
    user = Profesor.objects.filter(pk=user_id).first()
    if user != None:
        user.state = state
        user.save()
    return ''

def calendar(request, num_semana):
    num_semana = int(num_semana)
    user_id = request.session.get('user', None)
    user = Profesor.objects.filter(pk=user_id).first()
    if user != None:
        asesorias  = user.asesoria_set.all()
        semana = {
            'Horario': ['7-8', "8-9", '9-10', '10-11', '11-12', '12-13', '13-14', '14-15', '15-16', '16-17', '17-18', '18-19', '19-20', '20-21', '21-22'],
            'Lunes': ['']*15,
            'Martes': ['']*15,
            'Miércoles': ['']*15,
            'Jueves': ['']*15,
            'Viernes': ['']*15,
        }
        for asesoria in asesorias:
            semana[asesoria.fechaAsesoria][int(asesoria.horaInicio.hour) - 7] = "cita: " + asesoria.codCurso.nombreCurso + " - " + user.nombrepProfesor + " - " + asesoria.lugar.lugar

        args = {"semana": semana, "usuario": user, "num_semana": num_semana}

        if num_semana > 1:
            args["anterior"] = num_semana - 1
        if num_semana < 16:
            args["siguiente"] = num_semana + 1

        return render(request, 'profesor/Tony/calendar.html', args)
    return redirect('/profesor/login')


def perfil_profesor(request):
    comentarios = []
    total_rate = 0
    num_rate = 0

    user_id = request.session.get('user', None)
    user = Profesor.objects.filter(pk=user_id).first()
    if user != None:
        for asesoria in user.asesoria_set.all():
            for cita in asesoria.cita_set.all():
                for comentario in cita.comentario_set.all():
                    comentarios.append(comentario)
                    total_rate += comentario.rate
                    num_rate +=1
        rate = total_rate / num_rate if num_rate > 0 else " ** No hay Puntuación **"
        args = {"profesor": user, "comentarios": comentarios, "rate": rate}
        return render(request, 'profesor/Tony/perfil_profesor.html', args)
    return redirect('/profesor/login')


def log_out(request):
    try:
        del request.session['user']
        del request.session['type']
    except Exception as e:
        pass
    return redirect('/profesor/login')

templates/profesor/Tony/buscarAsesoria.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% block head %}
    <title>Bucar Asesoria</title>
    {% endblock %}
  </head>
  <body>
    {% block body %}
    <div class="container text-center">
  		<div class= "row">
  			<div>
  				<img margin-left="100" width="150" height="150" src="{% static 'images\logo.jpg' %}" />
  			</div>
  			<div class = "col-sm-4">
  				<br />
  				<br />
  				<h2 align-content: "center">Asesoria ULima</h2>
  			</div>
      </div>
     </div>
    {% endblock %}

  </body>
</html>

templates/profesor/Tony/calendar.html
{% extends "profesor/base.html" %}
{%load staticfiles %}

{% block title %} <title> Calendario </title>{% endblock %}

{% block body %}
  <div>
    <div class="container">
      <div class="row">
				<div class="col-3">
					{% if anterior %}
						<a href="{% url 'alumno:calendario' anterior %}"> < Semana Anterior</a>
					{% endif %}
				</div>
				<div class="col-6">
					<h3 class="text-center">Semana {{num_semana}}</h3>
				</div>
				<div class="col-3">
					{% if siguiente %}
						<p class="text-right"><a href="{% url 'alumno:calendario' siguiente %}"> Siguiente Semana ></a></p>

					{% endif %}
				</div>

			</div>
			<br>
			<div id="calendar">
				<div class="grid-container">
					{% for key, values in semana.items %}
						<div class="grid-item"> {{key}}</div>
						{% for value in values %}
							<div class="grid-item"> {{value}}</div>
						{% endfor %}
					{% endfor %}
				</div>
    </div>
	</div>
</div>
<div id="dropDownSelect1"></div>
{% endblock %}

templates/profesor/Tony/citas.html
{% extends "profesor/base.html" %}
{%load staticfiles %}

{% block title %} <title> Home </title>{% endblock %}

{% block body %}
  <div>
    <div class="container">
      <h4>ASESORIAS PROGRAMADAS</h4>
      <br>
              <table>
								<tr>
									<th>Alumno</th>
									<th>Curso</th>
									<th colspan="2">Fecha y Hora</th>
									<th>Lugar</th>
									<th>Acción</th>
								</tr>
                {% for asesoria in asesorias %}
									{% for cita in asesoria.cita_set.all %}
										<tr>
											<td>{{cita.alumno.nombre}}</td>
									    <td>{{asesoria.codCurso.nombreCurso}}</td>
									    <td>{{asesoria.fechaAsesoria}}</td>
											<td>{{asesoria.horaInicio|time:'H:i'}}</td>
									    <td>{{asesoria.lugar.lugar}}</td>
											<td>
												<a href="{% url 'profesor:eliminar_cita' cita.pk %}" class="btn btn-info" >Eliminar</a>
											</td>
									  </tr>
									{% endfor%}
                {% endfor%}
							</table>
            <hr>
			<br>
		</div>
	</div>
</div>
<div id="dropDownSelect1"></div>
{% endblock %}

templates/profesor/Tony/favoritos.html
{% extends "profesor/base.html" %}
{%load staticfiles %}

{% block title %} <title> Home </title>{% endblock %}

{% block body %}
	<div>
		<br />
	</div>
	<div class="container text-center">
		<div class= "row">
			<div>
				<a href="../home">
					<img margin-left="100" width="150" height="150" src="{% static 'images\logo.jpg' %}" />
				</a>
			</div>
			<div class = "col-sm-4">
				<br />
				<br />
				<h2 align-content: "center">Asesorias ULima</h2>
			</div>
			<div class = "col-sm-4">
				<br /><br />
				<p> Bienvenido {{usuario| upper}} </p>
				<p> ¿Que deseas hacer hoy? </p>
			</div>
					<div class = "col-sm-2">
						<a href="{% url 'profesor:log_out' %}" class="btn btn-warning">Log Off</a>
					</div>
	  </div>
	</div>

	<br />
	<br />

  <div>
    <div class="container">
      <h4>LISTA DE FAVORITOS</h4>
      <br>
      <ul>
            <li>
              <table>
								<tr>
									<th>Curso</th>
									<th colspan="2">Fecha y Hora</th>
									<th>Lugar</th>
									<th>Acción</th>
								</tr>
								{% for favorito in favoritos %}
									<tr>
								    <td>{{favorito.asesoria.codCurso.nombreCurso}}</td>
								    <td>{{favorito.asesoria.fechaAsesoria}}</td>
										<td>{{favorito.asesoria.horaInicio|time:'H:i'}}</td>
								    <td>{{favorito.asesoria.lugar.lugar}}</td>
										<td>
											<a href="{% url 'eliminar_favorito' favorito.pk %}" class="btn btn-info" >Eliminar</a>
										</td>
								  </tr>
                {% endfor%}
							</table>
            </li>
            <hr>
      </ul>
    </div>
	</div>
</div>
<div id="dropDownSelect1"></div>
{% endblock %}

templates/profesor/Tony/historial.html
{% extends "profesor/base.html" %}
{%load staticfiles %}

{% block title %} <title> Historial </title>{% endblock %}

{% block body %}
  <div>
    <div class="container">
			<h4>ASESORIAS PASADAS</h4>
        <table>
					<tr>
						<th>Alumno</th>
						<th>Curso</th>
						<th colspan="2">Fecha y Hora</th>
						<th>Lugar</th>
						<th>Acción</th>
					</tr>
          {% for asesoria in asesorias %}
						{% for cita in asesoria.cita_set.all %}
							<tr>
								<td>{{cita.alumno.nombre}}</td>
						    <td>{{asesoria.codCurso.nombreCurso}}</td>
						    <td>{{asesoria.fechaAsesoria}}</td>
								<td>{{asesoria.horaInicio|time:'H:i'}}</td>
						    <td>{{asesoria.lugar.lugar}}</td>
								<td>
									<a href="{% url 'profesor:eliminar_cita' cita.pk %}" class="btn btn-info" >Eliminar</a>
								</td>
						  </tr>
						{% endfor%}
          {% endfor%}
				</table>
        <hr>
	</div>
</div>
<div id="dropDownSelect1"></div>
{% endblock %}

templates/profesor/Tony/home.html
{% extends "profesor/base.html" %}
{%load staticfiles %}

{% block title %} <title> Home </title>{% endblock %}

{% block body %}


  <div>
    <div class="container">
			<div class="row">

        <div class="col-lg-4 col-md-6 col-sm-12">
					 <a href="../citas" class="btn btn-squared-default btn-warning btn-block">
						<i class="fa fa-pencil fa-5x"></i>
						<br />
						Citas Reservadas
						</a>
					</div>

					<div class="col-lg-4 col-md-6 col-sm-12">
						<a href="{% url 'profesor:calendario' num_semana %}" class="btn btn-squared-default btn-danger btn-block">
                <i class="fa fa-barcode fa-5x"></i>
                <br />
                Calendario
            </a>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-12">
                <a href="../historial" class="btn btn-squared-default btn-warning btn-block">
                    <i class="fa fa-mobile fa-5x"></i>
                    <br />
                    Historial
                </a>
					</div>

				<div class="col-lg-4 col-md-6 col-sm-12">
                <a href="../perfil_profesor" class="btn btn-squared-default-plain btn-success btn-block">
                    <i class="fa fa-user fa-5x"></i>
                    <br />
                    Perfil
                </a>
					</div>
				<div class="col-lg-4 col-md-6 col-sm-12">
                <a href="../ayuda" class="btn btn-squared-default-plain btn-info btn-block">
                    <i class="fa fa-compass fa-5x"></i>
                    <br />
                    Ayuda
                </a>
				</div>
        </div>
    </div>
		</div>
</div>


	<div id="dropDownSelect1"></div>
{% endblock %}

templates/profesor/Tony/lista_profesores.html
{% extends "profesor/base.html" %}
{%load staticfiles %}

{% block title %} <title> Home </title>{% endblock %}

{% block body %}
	<div>
		<br />
	</div>
	<div class="container text-center">
		<div class= "row">
			<div>
				<a href="../home">
					<img margin-left="100" width="150" height="150" src="{% static 'images\logo.jpg' %}" />
				</a>
			</div>
			<div class = "col-sm-4">
				<br />
				<br />
				<h2 align-content: "center">Asesorias ULima</h2>
			</div>
			<div class = "col-sm-4">
				<br /><br />
				<p> Bienvenido {{usuario.nombre| upper}} </p>
				<p> ¿Que deseas hacer hoy? </p>
			</div>
					<div class = "col-sm-2">
						<a href="{% url 'profesor:log_out' %}" class="btn btn-warning">Log Off</a>
					</div>
	  </div>
	</div>

	<br />
	<br />

  <div>
    <div class="container">
      <h4>LISTA DE PROFESORES</h4>
      <br>
			{% if var1 %}
				<div style="color:red;">YA HA SIDO ELEGIDA ESA ASESORÍA</div>
			{% endif %}
      <ul>
        {% for profesor in profesores %}
            <li>
              <div class="row">
                <p class="col-4">Nombre: {{profesor.nombrepProfesor}}</p>
                <p class="col-4">Correo: {{profesor.correo}}</p>
                <p class="col-4">Codigo: {{profesor.codProfesor}}</p>
              </div>
              <table>
								<tr>
									<th>Curso</th>
									<th colspan="2">Fecha y Hora</th>
									<th>Lugar</th>
									<th>Acción</th>
								</tr>
                {% for asesoria in profesor.asesoria_set.all %}
								{{asesoria.added}}
									<tr>
								    <td>{{asesoria.codCurso.nombreCurso}}</td>
								    <td>{{asesoria.fechaAsesoria}}</td>
										<td>{{asesoria.horaInicio|time:'H:i'}}</td>
								    <td>{{asesoria.lugar.lugar}}</td>
										<td>
											<a href="{% url 'agregar_cita' asesoria.codAsesoria %}" class="btn btn-info" >Seleccionar</a>
											<a href="{% url 'agregar_favorito' asesoria.codAsesoria %}" class="btn btn-warning" >Favorito</a>
										</td>
								  </tr>
                {% endfor%}
							</table>
            </li>
            <hr>
        {% endfor %}
      </ul>
    </div>
	</div>
</div>
<div id="dropDownSelect1"></div>
{% endblock %}

templates/profesor/Tony/perfil_profesor.html
{% extends "alumno/base.html" %}
{%load staticfiles %}

{% block title %} <title> Asesorías </title>{% endblock %}

{% block body %}
	<div>
		<br />
	</div>
	<div class="container text-center">
		<div class= "row">
			<div>
				<a href="../home">
					<img margin-left="100" width="150" height="150" src="{% static 'images\logo.jpg' %}" />
				</a>
			</div>
			<div class = "col-sm-4">
				<br />
				<br />
				<h2 align-content: "center">Asesorias ULima</h2>
			</div>
			<div class = "col-sm-4">
				<br /><br />
				<p> Bienvenido {{profesor.nombrepProfesor| upper}} </p>
				<p> ¿Que deseas hacer hoy? </p>
			</div>
					<div class = "col-sm-2">
						<a href="{% url 'alumno:log_out' %}" class="btn btn-warning">Log Off</a>
					</div>
	  </div>
	</div>

	<br />
	<br />

  <div>
    <div class="container">
			<div class="row">
				<div class="col-8">
					<h4>Información</h4>
					<br>
					<h6>Nombre: {{profesor.nombrepProfesor | upper}}</h6>
					<h6>Código: {{profesor.codigoUlima | upper}}</h6>
					<h6>Email: {{profesor.email}}</h6>
					<h6>Estado: {{profesor.state}}</h6>
					<h6>Puntuación: {{rate}}</h6>
					<br>

					<h4>Cursos</h4>
					<br>
					<ul>
						{% for asesoria in profesor.asesoria_set.all %}
							<li>
								- Curso: {{asesoria.codCurso.nombreCurso}} /
								Fecha: {{asesoria.fechaAsesoria}} /
								Hora: {{asesoria.horaInicio|time:'H:i'}} /
								Lugar: {{asesoria.lugar.lugar}}
							</li>
						{% endfor %}
					</ul>
					<br>

					<h4>Comentarios</h4>
					<br>
					<ul>
						{% for comentario in comentarios %}
							<div class="card">
								<div class="card-body">
									<h5 class="card-title">Curso: {{comentario.cita.asesoria.codCurso.nombreCurso}}</h5>
									<h6 class="card-subtitle mb-2 text-muted">Puntuación: {{comentario.rate}} estrellas</h6>
									<p class="card-text">{{comentario.comment}}</p>
								</div>
							</div>

						{% empty %}
						  ** No hay comentarios **
						{% endfor %}
					</ul>
				</div>
				<div class="col-4">
					<h5>Foto:</h5>
					<br>
					<img style="display:block; margin:0 auto; width:100%;"src="{{profesor.image.url}}" />
				</div>
			</div>
			<br>
    </div>
	</div>
</div>


<div id="dropDownSelect1"></div>

{% endblock %}