alumno/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import login


app_name = 'alumno'
urlpatterns = [

    path('home/', views.home, name="home"),
    path('lista_profesores/', views.lista_profesores, name="lista_profesores"),
    path('calendario/(?P<num_semana>\d+)/', views.calendar, name="calendario"),
    path('favoritos/', views.favoritos, name="favoritos"),
    path('historial/', views.historial, name="historial"),
    path('register/', views.register, name='register'),
    path('login/',  views.login, name='login'),
    path('log_out/',  views.log_out, name='log_out'),



    path('perfil_profesor/(?P<pk_profesor>\w+)/', views.perfil_profesor, name="perfil_profesor"),
    path('agregar_cita/(?P<asesoria>\w+)/', views.agregar_cita, name="agregar_cita"),
    path('agregar_favorito/(?P<asesoria>\w+)/', views.agregar_favorito, name="agregar_favorito"),
    path('eliminar_favorito/(?P<favorito>\w+)/', views.eliminar_favorito, name="eliminar_favorito"),
    path('eliminar_cita/(?P<cita>\w+)/', views.eliminar_cita, name="eliminar_cita"),
    path('finalizar_cita/(?P<cita>\w+)/', views.finalizar_cita, name="finalizar_cita"),

]

asesoria/urls.py
from django.contrib import admin
from django.urls import path, include
from asesoria import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.login_redirect, name='login_redirect'),
    path('admin/', admin.site.urls),
    path('alumno/', include('alumno.urls', namespace='alumno')),
    path('profesor/', include('profesor.urls', namespace='profesor')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

alumno/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from  profesor.models import *
#from django.contrib.auth.model import User
# Create your models here.

#class UserProfile(models.Model):

#    USERS_TYPE = ('Alumno','Profesor')

    #user = models.OnetoOneField(User)
    #tipo = (models.chartField(max_legnth=10, choices = USERS_TYPE))
    #carrera = models.chartField(default=10)

class Alumno(models.Model):
    nombre = models.CharField(max_length=60)
    apellido = models.CharField(max_length=50)
    password = models.CharField(max_length=20)
    codigoUlima  = models.CharField(max_length=20, unique=True)
    email  = models.CharField(max_length=30, unique=True)


    def __str__(self):
        return "PK: {}, Nombre: {}, Código: {}".format(self.pk, self.nombre, self.codigoUlima)

    @staticmethod
    def verify_user(codigoUlima, password):
        alumno = Alumno.objects.filter(codigoUlima=codigoUlima).first()
        return alumno != None and alumno.password == password, alumno

class Cita(models.Model):
    asesoria = models.ForeignKey(Asesoria, on_delete=models.CASCADE)
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)
    semana = models.IntegerField()
    finalizado = models.BooleanField(default=False)
    #PUEDE MEJORARSE
    tema = models.CharField(max_length=300)

    class Meta:
        unique_together = ('asesoria', 'alumno',)

    def __str__(self):
        return "Asesoria: {}, Alumno: {}".format(self.asesoria, self.alumno)


class Favorito(models.Model):
    asesoria = models.ForeignKey(Asesoria, on_delete=models.CASCADE)
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('asesoria', 'alumno',)

    def __str__(self):
        return "Asesoria: {}, Alumno: {}".format(self.asesoria, self.alumno)


class Comentario(models.Model):

    cita = models.ForeignKey(Cita, on_delete=models.CASCADE)
    rate = models.IntegerField()
    comment = models.CharField(max_length = 200)

profesor/models.py
from django.db import models
# Create your models here.


class Profesor(models.Model):

    state_options = (
        ('Disponible', 'Disponible'),
        ('Ocupado', 'Ocupado'),
        ('Ausente', 'Ausente'),
        ('No disponible', 'No disponible'),
    )

    nombrepProfesor = models.CharField(max_length=60)
    password = models.CharField(max_length=20)
    codigoUlima  = models.CharField(max_length=20, unique=True)
    email  = models.CharField(max_length=30, unique=True)
    state = models.CharField(max_length=20, choices=state_options)
    image = models.ImageField(upload_to="profesores/")

    def __str__(self):
        return "PK: {}, Nombre: {}, Código ULima: {}".format(self.pk, self.nombrepProfesor, self.codigoUlima)

    @staticmethod
    def verify_user(codigoUlima, password):
        profesor = Profesor.objects.filter(codigoUlima=codigoUlima).first()
        return profesor != None and profesor.password == password, profesor

class Curso(models.Model):
    nombreCurso = models.CharField(max_length=50)
    seccion = models.IntegerField()
    codProfesor = models.ForeignKey(Profesor, on_delete=models.CASCADE)

    def __str__(self):
        return "Nombre del Curso: {}".format(self.nombreCurso)

class Salon(models.Model):
    lugar = models.CharField(max_length = 10, unique= True)

    def __str__(self):
        return "Lugar: {}".format(self.lugar)

class Asesoria(models.Model):
    dia_semana = (
        ('Lunes', 'Lunes'),
        ('Martes', 'Martes'),
        ('Miércoles', 'Miércoles'),
        ('Jueves', 'Jueves'),
        ('Viernes', 'Viernes'),
    )

    codProfesor = models.ForeignKey( Profesor, on_delete=models.CASCADE)
    codCurso= models.ForeignKey(Curso, on_delete=models.CASCADE,)
    fechaAsesoria = models.CharField(max_length=12, choices=dia_semana)
    horaInicio = models.TimeField(default="12:00")
    lugar = models.ForeignKey(Salon, on_delete=models.CASCADE)

    def __str__(self):
        return "PK: {}, Profesor: {}, Curso".format(self.pk, self.codProfesor, self.codCurso)

alumno/forms.py
from django import forms
from alumno.models import *
# from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)


    class Meta:
        model = User
        fields = {
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        }

class LoginForm(forms.Form):
    codigoUlima = forms.CharField(label='Código ULima', required=True)
    password = forms.CharField(label='Contraseña', required=True)

    class Meta:
        model = Alumno
        fields = {
            'codigoUlima',
            'password'
        }

alumno/views.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from alumno.forms import *
from alumno.models import *
from profesor.models import *
import datetime

#               Utils

inicio_clases = datetime.datetime(2018, 8, 6)

#######################################


ALUMNO = 'ALUMNO'

# Create your views here.
def home(request):
    delta_date = datetime.datetime.now() - inicio_clases
    num_semana = round(delta_date.days / 7)
    user_id = request.session.get('user', None)
    type = request.session.get('type', None)
    if type == ALUMNO:
        user = Alumno.objects.filter(pk=user_id).first()
        if user != None:
            return render(request,'alumno/Tony/home.html', {"usuario": user, "num_semana": num_semana})
    return redirect('/alumno/login')



def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            codigoUlima = form.cleaned_data['codigoUlima']
            password = form.cleaned_data['password']
            boo, alumno = Alumno.verify_user(codigoUlima, password)
            if boo:
                request.session['user'] = alumno.pk
                request.session['type'] = ALUMNO
                return redirect('/alumno/home')

    form = LoginForm()
    args = {'form': form}
    return render(request,'alumno/login.html', args)

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/alumno/login')
        print(form.errors)

    else:
        form = RegistrationForm()
        args = {'form': form}
        return render(request, 'alumno/reg_form.html', args)


def lista_profesores(request):
    user_id = request.session.get('user', None)
    user = Alumno.objects.filter(pk=user_id).first()
    if user != None:
        print(user.cita_set.all())
        profesores = Profesor.objects.all()
        args = {"profesores": profesores, "usuario": user}
        return render(request, 'alumno/Tony/lista_profesores.html', args)
    return redirect('/alumno/login')

def perfil_profesor(request, pk_profesor):
    profesor = Profesor.objects.get(pk= pk_profesor)
    comentarios = []
    total_rate = 0
    num_rate = 0
    for asesoria in profesor.asesoria_set.all():
        for cita in asesoria.cita_set.all():
            for comentario in cita.comentario_set.all():
                comentarios.append(comentario)
                total_rate += comentario.rate
                num_rate +=1


    rate = total_rate / num_rate if num_rate > 0 else " ** No hay Puntuación **"
    args = {"profesor": profesor, "comentarios": comentarios, "rate": rate}
    return render(request, 'alumno/Tony/perfil_profesor.html', args)

def calendar(request, num_semana):
    num_semana = int(num_semana)
    user_id = request.session.get('user', None)
    user = Alumno.objects.filter(pk=user_id).first()
    if user != None:
        citas  = user.cita_set.all()
        favoritos = user.favorito_set.all()
        semana = {
            'Horario': ['7-8', "8-9", '9-10', '10-11', '11-12', '12-13', '13-14', '14-15', '15-16', '16-17', '17-18', '18-19', '19-20', '20-21', '21-22'],
            'Lunes': ['']*15,
            'Martes': ['']*15,
            'Miércoles': ['']*15,
            'Jueves': ['']*15,
            'Viernes': ['']*15,
        }
        for favorito in favoritos:
            asesoria = favorito.asesoria
            semana[asesoria.fechaAsesoria][int(asesoria.horaInicio.hour) - 7] = "Favorito: " + asesoria.codCurso.nombreCurso + " - " + asesoria.codCurso.codProfesor.nombrepProfesor + " - " + asesoria.lugar.lugar
        for cita in citas:
            if cita.semana == num_semana:
                asesoria = cita.asesoria
                semana[asesoria.fechaAsesoria][int(asesoria.horaInicio.hour) - 7] = "Cita: " + asesoria.codCurso.nombreCurso + " - " + asesoria.codCurso.codProfesor.nombrepProfesor + " - " + asesoria.lugar.lugar

        profesores = Profesor.objects.all()
        args = {"semana": semana, "usuario": user, "num_semana": num_semana}

        if num_semana > 1:
            args["anterior"] = num_semana - 1
        if num_semana < 16:
            args["siguiente"] = num_semana + 1

        return render(request, 'alumno/Tony/calendar.html', args)
    return redirect('/alumno/login')

def favoritos(request):
    user_id = request.session.get('user', None)
    user = Alumno.objects.filter(pk=user_id).first()
    if user != None:
        favoritos = user.favorito_set.all()
        args = {"favoritos": favoritos, "usuario": user}
        return render(request, 'alumno/Tony/favoritos.html', args)
    return redirect('/alumno/login')

def historial(request):
    user_id = request.session.get('user', None)
    user = Alumno.objects.filter(pk=user_id).first()
    if user != None:
        citas = user.cita_set.all()
        args = {"citas": citas, "usuario": user}
        return render(request, 'alumno/Tony/historial.html', args)
    return redirect('/alumno/login')

def agregar_cita(request, asesoria):
    try:
        user_id = request.session.get('user', None)
        user = Alumno.objects.filter(pk=user_id).first()
        if user != None:
            delta_date = datetime.datetime.now() - inicio_clases
            num_semana = round(delta_date.days / 7)
            asesoria = Asesoria.objects.get(pk = asesoria)
            cita = Cita.objects.create(asesoria=asesoria, alumno=user, semana=num_semana, tema="")
    except Exception as e:
        print(e)
    # print(codCita)
    # print(Cita.objects.get(pk=codCita))
    # return render(request, 'Tony/lista_profesores.html', args)
    profesores = Profesor.objects.all()
    args = {"profesores": profesores, "usuario": request.user, "success": True}
    return render(request, 'alumno/Tony/lista_profesores.html', args)

def agregar_favorito(request, asesoria):
    try:
        user_id = request.session.get('user', None)
        user = Alumno.objects.filter(pk=user_id).first()
        if user != None:
            asesoria = Asesoria.objects.get(pk = asesoria)
            favorito = Favorito.objects.create(asesoria=asesoria, alumno=user)
    except Exception as e:
        pass
    # print(codCita)
    # print(Cita.objects.get(pk=codCita))
    # return render(request, 'Tony/lista_profesores.html', args)
    profesores = Profesor.objects.all()
    args = {"profesores": profesores, "usuario": request.user}
    return redirect('/alumno/lista_profesores')


def eliminar_favorito(request, favorito):
    Favorito.objects.get(pk=favorito).delete()
    return redirect('/alumno/favoritos')

def eliminar_cita(request, cita):
    Cita.objects.get(pk=cita).delete()
    return redirect('/alumno/historial')

@csrf_exempt
def finalizar_cita(request, cita):
    user_id = request.session.get('user', None)
    user = Alumno.objects.filter(pk=user_id).first()
    if user != None:
        print(user)
        if request.method == 'POST':
            cita = Cita.objects.get(pk = cita)
            Comentario.objects.create(cita= cita, rate = request.POST['rate'], comment= request.POST['comment'])
            cita.finalizado = True
            cita.save()
            return redirect('/alumno/home')
        elif request.method == 'GET':
            return render(request, 'alumno/Tony/finalizar_cita.html', {"cita": cita, "usuario": user})
    else:
        return redirect('/alumno/login')


def log_out(request):
    try:
        del request.session['user']
        del request.session['type']
    except Exception as e:
        pass
    return redirect('/alumno/login')

templates/alumno/Tony/calendar.html
{% extends "alumno/base.html" %}
{%load staticfiles %}

{% block title %} <title> Calendario </title>{% endblock %}

{% block body %}
	<div>
		<br />
	</div>
	<div class="container text-center">
		<div class= "row">
			<div>
				<a href="{% url 'alumno:home' %}">
					<img margin-left="100" width="150" height="150" src="{% static 'images\logo.jpg' %}" />
				</a>
			</div>
			<div class = "col-sm-4">
				<br />
				<br />
				<h2 align-content: "center">Asesorias ULima</h2>
			</div>
			<div class = "col-sm-4">
				<br /><br />
				<p> Bienvenido {{usuario.nombre|upper}} </p>
				<p> ¿Que deseas hacer hoy? </p>
			</div>
					<div class = "col-sm-2">
						<a href="{% url 'alumno:log_out' %}" class="btn btn-warning">Log Off</a>
					</div>
	  </div>
	</div>

	<br />
	<br />

  <div>
    <div class="container">
			<div class="row">
				<div class="col-3">
					{% if anterior %}
						<a href="{% url 'alumno:calendario' anterior %}"> < Semana Anterior</a>
					{% endif %}
				</div>
				<div class="col-6">
					<h3 class="text-center">Semana {{num_semana}}</h3>
				</div>
				<div class="col-3">
					{% if siguiente %}
						<p class="text-right"><a href="{% url 'alumno:calendario' siguiente %}"> Siguiente Semana ></a></p>

					{% endif %}
				</div>

			</div>
			<br>
			<div id="calendar">
				<div class="grid-container">
					{% for key, values in semana.items %}
						<div class="grid-item"> {{key}}</div>
						{% for value in values %}
							<div class="grid-item"> {{value}}</div>
						{% endfor %}
					{% endfor %}
				</div>
			</div>
    </div>
	</div>
</div>
<div id="dropDownSelect1"></div>
{% endblock %}

templates/alumno/Tony/favoritos.html
{% extends "alumno/base.html" %}
{%load staticfiles %}

{% block title %} <title> Favoritos </title>{% endblock %}

{% block body %}
	<div>
		<br />
	</div>
	<div class="container text-center">
		<div class= "row">
			<div>
				<a href="../home">
					<img margin-left="100" width="150" height="150" src="{% static 'images\logo.jpg' %}" />
				</a>
			</div>
			<div class = "col-sm-4">
				<br />
				<br />
				<h2 align-content: "center">Asesorias ULima</h2>
			</div>
			<div class = "col-sm-4">
				<br /><br />
				<p> Bienvenido {{usuario.nombre| upper}} </p>
				<p> ¿Que deseas hacer hoy? </p>
			</div>
					<div class = "col-sm-2">
						<a href="{% url 'alumno:log_out' %}" class="btn btn-warning">Log Off</a>
					</div>
	  </div>
	</div>

	<br />
	<br />

  <div>
    <div class="container">
      <h4>LISTA DE FAVORITOS</h4>
      <br>
      <ul>
            <li>
              <table>
								<tr>
									<th>Curso</th>
									<th colspan="2">Fecha y Hora</th>
									<th>Lugar</th>
									<th>Acción</th>
								</tr>
								{% for favorito in favoritos %}
									<tr>
								    <td>{{favorito.asesoria.codCurso.nombreCurso}}</td>
								    <td>{{favorito.asesoria.fechaAsesoria}}</td>
										<td>{{favorito.asesoria.horaInicio|time:'H:i'}}</td>
								    <td>{{favorito.asesoria.lugar.lugar}}</td>
										<td>
											<a href="{% url 'alumno:eliminar_favorito' favorito.pk %}" class="btn btn-info" >Eliminar</a>
										</td>
								  </tr>
                {% endfor%}
							</table>
            </li>
            <hr>
      </ul>
    </div>
	</div>
</div>
<div id="dropDownSelect1"></div>
{% endblock %}

templates/alumno/Tony/finalizar_cita.html
{% extends "alumno/base.html" %}
{%load staticfiles %}

{% block title %} <title> Asesorías </title>{% endblock %}

{% block body %}
	<div>
		<br />
	</div>
	<div class="container text-center">
		<div class= "row">
			<div>
				<a href="../../home">
					<img margin-left="100" width="150" height="150" src="{% static 'images\logo.jpg' %}" />
				</a>
			</div>
			<div class = "col-sm-4">
				<br />
				<br />
				<h2 align-content: "center">Asesorias ULima</h2>
			</div>
			<div class = "col-sm-4">
				<br /><br />
				<p> Bienvenido {{usuario.nombre| upper}} </p>
				<p> ¿Que deseas hacer hoy? </p>
			</div>
					<div class = "col-sm-2">
						<a href="{% url 'alumno:log_out' %}" class="btn btn-warning">Log Off</a>
					</div>
	  </div>
	</div>

	<br />
	<br />

  <div>
    <div class="container">
			<br>
			<form method="post">
			  <div class="form-group">
			    <label for="exampleInputEmail1">Comentario</label>
			    <input name="comment" type="text" class="form-control" placeholder="Ingresa un comentario" required>
			  </div>
				<div class="form-group">
			    <label for="exampleFormControlSelect1">Puntuación</label>
			    <select name="rate" class="form-control" id="exampleFormControlSelect1" required>
			      <option>1</option>
			      <option>2</option>
			      <option>3</option>
			      <option>4</option>
			      <option>5</option>
			    </select>
			  </div>
			  <button type="submit" class="btn btn-primary">Submit</button>
			</form>
    </div>
	</div>
</div>


<div id="dropDownSelect1"></div>

{% endblock %}

templates/alumno/Tony/historial.html
{% extends "alumno/base.html" %}
{%load staticfiles %}

{% block title %} <title> Historial </title>{% endblock %}

{% block body %}
	<div>
		<br />
	</div>
	<div class="container text-center">
		<div class= "row">
			<div>
				<a href="../home">
					<img margin-left="100" width="150" height="150" src="{% static 'images\logo.jpg' %}" />
				</a>
			</div>
			<div class = "col-sm-4">
				<br />
				<br />
				<h2 align-content: "center">Asesorias ULima</h2>
			</div>
			<div class = "col-sm-4">
				<br /><br />
				<p> Bienvenido {{usuario.nombre| upper}} </p>
				<p> ¿Que deseas hacer hoy? </p>
			</div>
					<div class = "col-sm-2">
						<a href="{% url 'alumno:log_out' %}" class="btn btn-warning">Log Off</a>
					</div>
	  </div>
	</div>

	<br />
	<br />

  <div>
    <div class="container">
      <h4>ASESORIAS PROGRAMADAS</h4>
			{% if success %}
				<h3 class="text-center" style="color:orange">**La asesoría fue eliminada exitosamente**</h3>
			{% endif %}
      <br>
              <table>
								<tr>
									<th>Profesor</th>
									<th>Curso</th>
									<th colspan="2">Fecha y Hora</th>
									<th>Lugar</th>
									<th>Acción</th>
								</tr>
                {% for cita in citas %}
									{% if not cita.finalizado %}
										<tr>
											<td>{{cita.asesoria.codProfesor.nombrepProfesor}}</td>
									    <td>{{cita.asesoria.codCurso.nombreCurso}}</td>
									    <td>{{cita.asesoria.fechaAsesoria}}</td>
											<td>{{cita.asesoria.horaInicio|time:'H:i'}}</td>
									    <td>{{cita.asesoria.lugar.lugar}}</td>
											<td>
												<a href="{% url 'alumno:eliminar_cita' cita.pk %}" class="btn btn-info" >Eliminar</a>
												<a href="{% url 'alumno:finalizar_cita' cita.pk %}" class="btn btn-warning" >Finalizar</a>
											</td>
									  </tr>
									{% endif %}
                {% endfor%}
							</table>
            <hr>
			<br>
			<h4>ASESORIAS PASADAS</h4>
			<ul></ul>
		</div>
	</div>
</div>


	<div id="dropDownSelect1"></div>
{% endblock %}

templates/alumno/Tony/home.html
{% extends "alumno/base.html" %}
{%load staticfiles %}

{% block title %} <title> Home </title>{% endblock %}

{% block body %}
	<div>
		<br />
	</div>
	<div class="container text-center">
		<div class= "row">
			<div>
				<img margin-left="100" width="150" height="150" src="{% static 'images\logo.jpg' %}" />
			</div>
			<div class = "col-sm-4">
				<br />
				<br />
				<h2 align-content: "center">Asesorias ULima</h2>
			</div>
			<div class = "col-sm-4">
				<br /><br />
				<p> Bienvenido {{usuario.nombre|upper}} </p>
				<p> ¿Que deseas hacer hoy? </p>
			</div>
					<div class = "col-sm-2">
						<a href="{% url 'alumno:log_out' %}" class="btn btn-warning">Log Off</a>
					</div>
	  </div>
	</div>

	<br />
	<br />

  <div>
    <div class="container">
			<div class="row">

        <div class="col-lg-4 col-md-6 col-sm-12">
					 <a href="{% url 'alumno:lista_profesores' %}" class="btn btn-squared-default btn-warning btn-block">
						<i class="fa fa-pencil fa-5x"></i>
						<br />
						Buscar Asesoria
						</a>
					</div>

					<div class="col-lg-4 col-md-6 col-sm-12">
						<a href="{% url 'alumno:calendario' num_semana %}" class="btn btn-squared-default btn-danger btn-block">
                <i class="fa fa-barcode fa-5x"></i>
                <br />
                Calendario
            </a>
					</div>
					<div class="col-lg-4 col-md-6 col-sm-12">
                <a href="{% url 'alumno:historial' %}" class="btn btn-squared-default btn-secondary btn-block">
                    <i class="fa fa-mobile fa-5x"></i>
                    <br />
                    Historial
                </a>
					</div>

        <div class="col-lg-4 col-md-6 col-sm-12">

							  <a href="{% url 'alumno:favoritos' %}"class="btn btn-squared-default-plain btn-success btn-block">
									<i class="fa fa-bell fa-5x"></i>
									<br />
									Favoritos
							  </a>
					</div>

				<div class="col-lg-4 col-md-6 col-sm-12">
                <a href="../ayuda" class="btn btn-squared-default-plain btn-info btn-block">
                    <i class="fa fa-compass fa-5x"></i>
                    <br />
                    Ayuda
                </a>
				</div>
        </div>
    </div>
		</div>
</div>
<div id="dropDownSelect1"></div>
{% endblock %}

templates/alumno/Tony/lista_profesores.html
{% extends "alumno/base.html" %}
{%load staticfiles %}

{% block title %} <title> Asesorías </title>{% endblock %}

{% block body %}
	<div>
		<br />
	</div>
	<div class="container text-center">
		<div class= "row">
			<div>
				<a href="{% url 'alumno:home' %}">
					<img margin-left="100" width="150" height="150" src="{% static 'images\logo.jpg' %}" />
				</a>
			</div>
			<div class = "col-sm-4">
				<br />
				<br />
				<h2 align-content: "center">Asesorias ULima</h2>
			</div>
			<div class = "col-sm-4">
				<br /><br />
				<p> Bienvenido {{usuario.nombre| upper}} </p>
				<p> ¿Que deseas hacer hoy? </p>
			</div>
					<div class = "col-sm-2">
						<a href="{% url 'alumno:log_out' %}" class="btn btn-warning">Log Off</a>
					</div>
	  </div>
	</div>

	<br />
	<br />

  <div>
    <div class="container">
      <h4>LISTA DE PROFESORES</h4>
			<br>
			<div class="form-group">
		    <label for="exampleInputEmail1">Buscar Profesor</label>
		    <input type="text" class="form-control" placeholder="Ingrese el nombre del profesor" oninput="buscarProfesor(this.value)">
		  </div>
			{% if success %}
				<h3 class="text-center" style="color:orange">**La asesoría fue registrada exitosamente**</h3>
			{% endif %}
			<br>
			{% if var1 %}
				<div style="color:red;">YA HA SIDO ELEGIDA ESA ASESORÍA</div>
			{% endif %}
      <ul id="lista_profesores">
        {% for profesor in profesores %}
            <li class={{profesor.nombrepProfesor}}>
              <div class="row">
                <p class="col-4">Nombre:

									<a href="{% url 'alumno:perfil_profesor' profesor.pk %}" ><u>{{profesor.nombrepProfesor}}</u></a>

								</p>
                <p class="col-4">Correo: {{profesor.email}}</p>
                <p class="col-4">Código: {{profesor.codigoUlima}}</p>
              </div>
              <table>
								<tr>
									<th>Curso</th>
									<th colspan="2">Fecha y Hora</th>
									<th>Lugar</th>
									<th>Acción</th>
								</tr>
                {% for asesoria in profesor.asesoria_set.all %}
								{{asesoria.added}}
									<tr>
								    <td>{{asesoria.codCurso.nombreCurso}}</td>
								    <td>{{asesoria.fechaAsesoria}}</td>
										<td>{{asesoria.horaInicio|time:'H:i'}}</td>
								    <td>{{asesoria.lugar.lugar}}</td>
										<td>
											{% if not asesoria.cita_set.all %}
												<a href="{% url 'alumno:agregar_cita' asesoria.pk %}" class="btn btn-info" >Seleccionar</a>
											{% endif %}
											<a href="{% url 'alumno:agregar_favorito' asesoria.pk %}" class="btn btn-warning" >Favorito</a>
										</td>
								  </tr>
                {% endfor%}
							</table>
            </li>
            <hr>
        {% endfor %}
      </ul>
    </div>
	</div>
</div>


<div id="dropDownSelect1"></div>

{% endblock %}

{% block extra_js %}

<script>
	function buscarProfesor(value){
		var children = $("#lista_profesores li")
		children.each( function (li){
			var atttribute = children[li].className.toLowerCase().startsWith(value.toLowerCase()) ? 'block' : 'none'
			children[li].setAttribute('style', "display: " + atttribute)
		})
	}

</script>

{% endblock %}